### ISSUE TITLE
installation steps?

### ISSUE THREAD

**Issue by alshaikh1** [ShehriyarQureshi/mobile-connect-profile#1]
any instruction of installation?

**Comment by thatdevsherry** [comment]
Hi,

I'll add the instructions now. I wasn't expecting anyone to try it out :smile:

**Comment by thatdevsherry** [comment]
I've updated the README to include some instructions on building and trying it out. I only have experience with Linux so that's what I've mentioned more about :smile: . Hope it helps out.

732ee4cede088910b79b0b0ec6398e8d369ce7bd

**Comment by alshaikh1** [comment]
great. is it OpenID certified implementation?

**Comment by thatdevsherry** [comment]
I've just started developing it. It's following the OpenID Connect Authorization Code Flow.

GSMA Mobile Connect is built upon OpenID Connect so it uses the OpenID Connect Authorization Code Flow but it has it's own profile i.e. some parameters that are optional in OpenID Connect are mandatory in Mobile Connect.

So no, it is not a complete OpenID Connect implementation let alone certified. Though I hope to understand the specification better and make it as close to the specifications as possible :smile: .

The Mobile Connect profile shouldn't deviate from OpenID Connect so I'm hoping I can make it to be in line with OpenID Connect Specifications while following the Mobile Connect Profile :smile:

**Comment by alshaikh1** [comment]
Perfect. That is the goal. I will try to run the code using Tomcat and see the Provider Metadata (.well-known/openid-configuration)

**Comment by alshaikh1** [comment]
upon GET /authorize?client_id=...
the browser is downloading a file called Authorize and it contains this text:
Initiate Authn

**Comment by thatdevsherry** [comment]
@alshaikh1 that's because it was sending a 200 OK response. I've fixed it to return a 302 response which, in a browser, will show an information page. The redirect will be in the header.

982e2ec4e813627ec7bc4fbd22741edad4797083

**Comment by alshaikh1** [comment]
OK now, the response is 302 but nothing is returning on browser. it says: File not found

Log:
127.0.0.1 - - [10/Jan/2019:11:53:08 +0200] "GET /mobile-connect-server/authorize?client_id=totally_not_shady&scope=i_wantz_hack&redirect_uri=http://wut.is.dis/boogabooga&response_type=code&version=1.1&state=123&nonce=456&correlation_id=789 HTTP/1.1" 302 24


however, 
Provider Metadata works fine at /.well-known/openid-configuration

**Comment by thatdevsherry** [comment]
The browser isn't supposed to show anything. The file not found is because of 302, which means it has to redirect somewhere which I haven't setup. I have yet to develop what it should do next.

**Comment by ShehriyarQureshi** [comment]
@alshaikh1 if you find an issue, create a new issue as this one is closed.

If you want some information about a specific behaviour like this one, you can email me. Lets try to keep the issues relevant. 😄
